name: Java CI

on: 
  push:
    paths: 
      - 'src/weather-service/**'

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file src/weather-service/pom.xml
    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Install Azure Spring Cloud extension
      run: az extension add -y --source https://azureclitemp.blob.core.windows.net/spring-cloud/spring_cloud-0.1.0-py2.py3-none-any.whl
    - name: Deploy to Azure Spring Cloud
      run: az spring-cloud app deploy --resource-group demo-azurespringcloud --service demospringcloud --name weather-service --jar-path src/weather-service/target/demo-0.0.1-SNAPSHOT.jar
